# Generated by Django 3.1.3 on 2020-11-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('celular', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=180)),
                ('bairro', models.CharField(max_length=120)),
                ('cep', models.IntegerField()),
                ('referencia', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
